### ISSUE TITLE
这个没维护了吗？跟官网的（历史更新日志 iOS网盟推广通用版）版本不一致

### ISSUE THREAD

**Issue by LiGuanWen** [baidumobsdk/iosmobsdk#1]
这个没维护了吗？跟官网的（历史更新日志 iOS网盟推广通用版）版本不一致

版本：V4.682020年03月23日
视频优化：封面图等交互细节优化，黑屏等bug修复
智能优选：新增视频模板；模板增加brandname渲染
信息流新增曝光回调、timeout等接口
IOS13和Xcode11适配
崩溃问题修复，解决bug和leak问题
版本：V4.672019年9月19日
IOS13适配(移除UIWebview,适配modalpresent等)，建议尽快更新
智能优选API和样式优化，可自定义title设置颜色、title设置字体、设置图片默认背景色
开屏、信息流、激励视频产品增加广告请求成功回调
视频贴片支持横竖屏切换
ANR卡顿问题解决，修复若干bug
版本：V4.662019年8月20日
信息流新增智能优选模板样式
竖版小视频开放是否缓存广告视频物料接口
全新SDK Demo样式和代码接入指南
新增Debug日志开关，可以设置是否显示SDK打印的log
全面优化广告内存泄露和占用问题，优化物料缓存策略
修复若干bug

这边还是 BaiduMobAdSDK (4.5.002)

pod 不支持最新的？

**Comment by baidumobsdk** [comment]
最新版已更新哦
