### ISSUE TITLE
版本 5.360 报错：Error (Xcode): Undefined symbol: OBJC_CLASS$_BaiduMobAdView

### ISSUE THREAD

**Issue by DoodleBears** [baidumobsdk/iosmobsdk#13]
# 背景信息
使用 Flutter 开发，iOS侧通过 Pod 接入
- pod BaiduMobAdSDK
编译无法通过，提示：
- `Error (Xcode): Undefined symbol: OBJC_CLASS$_BaiduMobAdView`

# 目前临时解决方式
- 切换为 5.352 就没有报错可以正常运行了

**Comment by baidumobsdk** [comment]
可以看下发版记录哈，这个view不维护了，下线了，很早之前就不维护了。
